"""Add is_bookmarked column to quotes table

Revision ID: b3c1c7671d84
Revises: 49bd525f58f4
Create Date: 2025-09-11 11:12:37.400646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c1c7671d84'
down_revision: Union[str, Sequence[str], None] = '49bd525f58f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('is_bookmarked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'is_bookmarked')
    # ### end Alembic commands ###
